# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/oem/GitHub/SimpleSDC/ui/material.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_materialDialog(object):
    def setupUi(self, materialDialog):
        materialDialog.setObjectName("materialDialog")
        materialDialog.resize(1520, 766)
        self.gridLayout = QtWidgets.QGridLayout(materialDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(materialDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_mat_uuid = QtWidgets.QLabel(self.frame)
        self.lbl_mat_uuid.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_mat_uuid.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_uuid.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_uuid.setObjectName("lbl_mat_uuid")
        self.horizontalLayout.addWidget(self.lbl_mat_uuid)
        self.tbx_mat_uuid = QtWidgets.QLineEdit(self.frame)
        self.tbx_mat_uuid.setReadOnly(True)
        self.tbx_mat_uuid.setObjectName("tbx_mat_uuid")
        self.horizontalLayout.addWidget(self.tbx_mat_uuid)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_mat_number = QtWidgets.QLabel(self.frame)
        self.lbl_mat_number.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_mat_number.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_number.setObjectName("lbl_mat_number")
        self.horizontalLayout_2.addWidget(self.lbl_mat_number)
        self.tbx_mat_number = QtWidgets.QLineEdit(self.frame)
        self.tbx_mat_number.setObjectName("tbx_mat_number")
        self.horizontalLayout_2.addWidget(self.tbx_mat_number)
        self.lbl_mat_name = QtWidgets.QLabel(self.frame)
        self.lbl_mat_name.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_mat_name.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_name.setObjectName("lbl_mat_name")
        self.horizontalLayout_2.addWidget(self.lbl_mat_name)
        self.tbx_mat_name = QtWidgets.QLineEdit(self.frame)
        self.tbx_mat_name.setObjectName("tbx_mat_name")
        self.horizontalLayout_2.addWidget(self.tbx_mat_name)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_mat_geo_lat = QtWidgets.QLabel(self.frame)
        self.lbl_mat_geo_lat.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_mat_geo_lat.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_geo_lat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_geo_lat.setObjectName("lbl_mat_geo_lat")
        self.horizontalLayout_3.addWidget(self.lbl_mat_geo_lat)
        self.tbx_mat_geo_lat = QtWidgets.QLineEdit(self.frame)
        self.tbx_mat_geo_lat.setObjectName("tbx_mat_geo_lat")
        self.horizontalLayout_3.addWidget(self.tbx_mat_geo_lat)
        self.lbl_mat_geo_lon = QtWidgets.QLabel(self.frame)
        self.lbl_mat_geo_lon.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_mat_geo_lon.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_geo_lon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_geo_lon.setObjectName("lbl_mat_geo_lon")
        self.horizontalLayout_3.addWidget(self.lbl_mat_geo_lon)
        self.tbx_mat_geo_lon = QtWidgets.QLineEdit(self.frame)
        self.tbx_mat_geo_lon.setObjectName("tbx_mat_geo_lon")
        self.horizontalLayout_3.addWidget(self.tbx_mat_geo_lon)
        self.lbl_mat_geo_alt = QtWidgets.QLabel(self.frame)
        self.lbl_mat_geo_alt.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_mat_geo_alt.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_geo_alt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_geo_alt.setObjectName("lbl_mat_geo_alt")
        self.horizontalLayout_3.addWidget(self.lbl_mat_geo_alt)
        self.tbx_mat_geo_alt = QtWidgets.QLineEdit(self.frame)
        self.tbx_mat_geo_alt.setObjectName("tbx_mat_geo_alt")
        self.horizontalLayout_3.addWidget(self.tbx_mat_geo_alt)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_mat_tmp_bgn = QtWidgets.QLabel(self.frame)
        self.lbl_mat_tmp_bgn.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_mat_tmp_bgn.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_tmp_bgn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_tmp_bgn.setObjectName("lbl_mat_tmp_bgn")
        self.horizontalLayout_4.addWidget(self.lbl_mat_tmp_bgn)
        self.tbx_mat_tmp_bgn = QtWidgets.QLineEdit(self.frame)
        self.tbx_mat_tmp_bgn.setObjectName("tbx_mat_tmp_bgn")
        self.horizontalLayout_4.addWidget(self.tbx_mat_tmp_bgn)
        self.lbl_mat_tmp_mid = QtWidgets.QLabel(self.frame)
        self.lbl_mat_tmp_mid.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_mat_tmp_mid.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_tmp_mid.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_tmp_mid.setObjectName("lbl_mat_tmp_mid")
        self.horizontalLayout_4.addWidget(self.lbl_mat_tmp_mid)
        self.tbx_mat_tmp_mid = QtWidgets.QLineEdit(self.frame)
        self.tbx_mat_tmp_mid.setObjectName("tbx_mat_tmp_mid")
        self.horizontalLayout_4.addWidget(self.tbx_mat_tmp_mid)
        self.lbl_mat_tmp_end = QtWidgets.QLabel(self.frame)
        self.lbl_mat_tmp_end.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_mat_tmp_end.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_tmp_end.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_tmp_end.setObjectName("lbl_mat_tmp_end")
        self.horizontalLayout_4.addWidget(self.lbl_mat_tmp_end)
        self.tbx_mat_tmp_end = QtWidgets.QLineEdit(self.frame)
        self.tbx_mat_tmp_end.setObjectName("tbx_mat_tmp_end")
        self.horizontalLayout_4.addWidget(self.tbx_mat_tmp_end)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_mat_description = QtWidgets.QLabel(self.frame)
        self.lbl_mat_description.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_mat_description.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_description.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_description.setObjectName("lbl_mat_description")
        self.horizontalLayout_5.addWidget(self.lbl_mat_description)
        self.tbx_mat_description = QtWidgets.QLineEdit(self.frame)
        self.tbx_mat_description.setObjectName("tbx_mat_description")
        self.horizontalLayout_5.addWidget(self.tbx_mat_description)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.btn_cnl = QtWidgets.QPushButton(self.frame)
        self.btn_cnl.setMinimumSize(QtCore.QSize(0, 48))
        self.btn_cnl.setMaximumSize(QtCore.QSize(250, 48))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/black/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cnl.setIcon(icon)
        self.btn_cnl.setIconSize(QtCore.QSize(24, 24))
        self.btn_cnl.setFlat(True)
        self.btn_cnl.setObjectName("btn_cnl")
        self.horizontalLayout_6.addWidget(self.btn_cnl)
        self.btn_ok = QtWidgets.QPushButton(self.frame)
        self.btn_ok.setMinimumSize(QtCore.QSize(0, 48))
        self.btn_ok.setMaximumSize(QtCore.QSize(250, 48))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icon/black/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ok.setIcon(icon1)
        self.btn_ok.setIconSize(QtCore.QSize(24, 24))
        self.btn_ok.setFlat(True)
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout_6.addWidget(self.btn_ok)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(materialDialog)
        QtCore.QMetaObject.connectSlotsByName(materialDialog)
        materialDialog.setTabOrder(self.tbx_mat_uuid, self.tbx_mat_number)
        materialDialog.setTabOrder(self.tbx_mat_number, self.tbx_mat_name)
        materialDialog.setTabOrder(self.tbx_mat_name, self.tbx_mat_geo_lat)
        materialDialog.setTabOrder(self.tbx_mat_geo_lat, self.tbx_mat_geo_lon)
        materialDialog.setTabOrder(self.tbx_mat_geo_lon, self.tbx_mat_geo_alt)
        materialDialog.setTabOrder(self.tbx_mat_geo_alt, self.tbx_mat_tmp_bgn)
        materialDialog.setTabOrder(self.tbx_mat_tmp_bgn, self.tbx_mat_tmp_mid)
        materialDialog.setTabOrder(self.tbx_mat_tmp_mid, self.tbx_mat_tmp_end)
        materialDialog.setTabOrder(self.tbx_mat_tmp_end, self.tbx_mat_description)

    def retranslateUi(self, materialDialog):
        _translate = QtCore.QCoreApplication.translate
        materialDialog.setWindowTitle(_translate("materialDialog", "Dialog"))
        self.lbl_mat_uuid.setText(_translate("materialDialog", "UUID : "))
        self.lbl_mat_number.setText(_translate("materialDialog", "資料番号 : "))
        self.lbl_mat_name.setText(_translate("materialDialog", "資料の名称 : "))
        self.lbl_mat_geo_lat.setText(_translate("materialDialog", "緯度 : "))
        self.lbl_mat_geo_lon.setText(_translate("materialDialog", "軽度 : "))
        self.lbl_mat_geo_alt.setText(_translate("materialDialog", "標高 : "))
        self.lbl_mat_tmp_bgn.setText(_translate("materialDialog", "開始時期 : "))
        self.lbl_mat_tmp_mid.setText(_translate("materialDialog", "中間時期 : "))
        self.lbl_mat_tmp_end.setText(_translate("materialDialog", "終了時期 : "))
        self.lbl_mat_description.setText(_translate("materialDialog", "備考 : "))
        self.btn_cnl.setText(_translate("materialDialog", "Cancel"))
        self.btn_ok.setText(_translate("materialDialog", "OK"))

